version: 2
updates:
  # See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build(deps)"
    ignore:
      - dependency-name: "attrs"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build(actions)"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build(pre-commit)"
    cooldown:
      default-days: 7
    groups:
      pre-commit:
        patterns:
          - "*"
