documentation:
- changed-files:
  - any-glob-to-any-file: ['doc/source/**/*', 'examples/**/*', 'README.rst']
maintenance:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', '.flake8', '.pre-commit-config.yaml', 'pyproject.toml', 'tox.ini']
dependencies:
- changed-files:
  - any-glob-to-any-file: ['pyproject.toml']
testing:
- changed-files:
  - any-glob-to-any-file: ['tests/**/*']
