# Copyright (C) 2023 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from contextlib import suppress
from enum import IntEnum
import glob
import os
from pathlib import Path
import re
import shutil

CONTAINER_DEFAULT_IMAGE_TAG = "v26.1.0"
CONTAINER_WORKING_DIR = "/home/cfx_work_dir"
CONTAINER_TEMP_DIR = "/tmp/pycfx_tests"


class TestExecutionMode(IntEnum):
    __test__ = False
    DIRECT = 0
    CONTAINERIZED = 1


def is_containerized_mode(pytestconfig) -> bool:
    return (
        os.getenv("PYCFX_LAUNCH_CONTAINER")
        or TestExecutionMode[pytestconfig.getoption("execution_mode")]
        == TestExecutionMode.CONTAINERIZED
    )


def get_image_tag(pytestconfig) -> str:
    return os.getenv("CFX_IMAGE_TAG", pytestconfig.getoption("image_tag"))


def get_container_cfx_version(image_tag: str) -> str:
    if cfx_version := re.match(r"^v(\d+(?:\.\d+)+)", image_tag):
        return cfx_version.group(1)
    else:
        return CONTAINER_DEFAULT_IMAGE_TAG[1:]


def fix_jointed_lines(s: str) -> str:
    """Fix spacing around equal signs in jointed lines."""
    return re.sub(r"\s+=\s+", " = ", s)


def ccl_join_continued_lines(ccl_lines):
    """
    A generator that joins ccl_lines that end with a backslash.

    Args:
        ccl_lines (iterable).

    Yields:
        str: The next joined line.
    """
    current_line = ""
    for line in ccl_lines:
        stripped_line = line.rstrip()

        if stripped_line.endswith("\\"):
            current_line += stripped_line[:-1]
        else:
            current_line += stripped_line
            yield fix_jointed_lines(current_line)
            current_line = ""

    # Last line
    if current_line:
        yield current_line


def read_ccl_from_file(ccl_file_path: str) -> list[str]:
    """
    Read a CCL file generated by the export_ccl command and return its lines.
    Skips the comment lines at the top of the file.
    """
    try:
        with open(ccl_file_path, "r") as ccl_file_object:
            lines = [l for l in ccl_join_continued_lines(ccl_file_object)]
            # The first three lines are comments
            if len(lines) > 3:
                return lines[3:]
            else:
                return []

    except FileNotFoundError:
        print(f"Error: The file at {ccl_file_path} was not found.")


def setup_write_dir(test_data_directory_path, files_to_remove=[]):

    # Make a temporary directory
    generated_path_engine = f"{test_data_directory_path}/generated"
    generated_path_client = Path(__file__).parent.parent / "generated"
    generated_path_client.mkdir(parents=True, exist_ok=True)

    # Remove files
    if files_to_remove:
        with suppress(FileNotFoundError):
            for pattern in files_to_remove:
                for f in glob.glob(str(generated_path_client / pattern)):
                    p = Path(f)
                    base = p.name
                    if base in (".", ".."):
                        continue
                    if p.is_file():
                        p.unlink()
                    elif p.is_dir():
                        shutil.rmtree(p)

    return generated_path_engine, str(generated_path_client)
